CONFIG_SERVICE_BASE_URL: "http://10.128.225.200:6602"     # Define remote Config URL for ConfigManager.java
APP_NAME: "TMIS_FINANCE_CONSUMER"                         # used for ConfigManager.java
BALALAIKA: "VODKA, Гладиолус"                             # test UTF-8
EXCHANGE_NAME: "TMIS_FINANCE_EXCHANGE"

financeWebservice:
  url: "http://dnosov-nb:8080/Mock_1Cwebservice?wsdl"
  targetNamespace: "http://schemas.xmlsoap.org/soap/envelope"
  name: "Exchange_MIS"

amqp:                                                     # Define AMQP connection properties
  host: "10.1.2.12"
  port: "5672"
  user: "tmis_finance"
  password: "rabbitrules!"
  consumeQueue:
    name: "queue.tmis.finance.invoice"
    durable: "true"
    autoDelete: "false"
    exclusive: "false"
    arguments: null
  consumer:
    tag: "TMIS_FINANCE_CONSUMER"
    prefetchCount: "5"
    uuid: "CAFEBABE-8126-4D33-BCD0-DF45F05FB8E8"

